// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdaeulrdesncpzapmisv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkYWV1bHJkZXNuY3B6YXBtaXN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NjUyMjQsImV4cCI6MjA2ODE0MTIyNH0.0_LlnV_ZDg3mEf1D47-2JIy9mcK1pVb_TKHVdn5dxv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});